apiVersion: apps/v1
kind: Deployment
metadata:
  name: nodejs-deployment
  namespace: development # change this to production if needed
spec:
  replicas: 2 # change this to the number of replicas you want
  selector:
    matchLabels:
      app: nodejs-app
  template:
    metadata:
      labels:
        app: nodejs-app
    spec:
      containers:
      - name: nodejs-app
        image: serverlab/simple-api:1.0.0 # change this to your image name and tag
        ports:
        - containerPort: 3000 # change this to the port your app listens on
